---
ID: "5bd0a94c-447e-4042-b3a7-ccce3b7d0752"
Parent: "fa3c818b-3b70-490a-bf49-f6d6a14e2b43"
Template: "fa3c818b-3b70-490a-bf49-f6d6a14e2b43"
Path: /sitecore/templates/Project/Group/Page Types/Event/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{17857EED-0386-4911-89EC-C29D9C018237}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-right"
          uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r
          id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}"
          ph="navbar-activity"
          uid="{462763BC-EC80-4FBA-9714-B63A87B43259}" />
        <r
          id="{2695013C-DD51-410B-9983-F271F16C727D}"
          ph="navbar-activity"
          uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r
          ds="{E3F5B510-54B3-4FEE-B7A8-0FBA14121AC1}"
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          ph="navbar-activity"
          uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r
          ds=""
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="Background&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{A3CA17FF-693C-46F1-87AA-B8C1833F1890}" />
        <r
          ds=""
          id="{CF750731-1275-4CC7-A9E6-809515CB4DD1}"
          par="Background&amp;ContainerIsFluid&amp;UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{25827F00-EC67-4908-AA1C-51DEB35AD9F8}" />
        <r
          id="{5FB2A01F-DE82-42C0-8EF0-887EE5D7387B}"
          ph="/page-layout/section/col-wide-1"
          uid="{B3196F02-0692-42C2-8643-F913B5283BEB}" />
        <r
          ds=""
          id="{EF4E87B3-5292-4EC8-B10C-8208AB81C8B3}"
          par=""
          ph="/page-layout/section/col-narrow-1"
          uid="{560DFB04-8432-4810-9A87-563FFFE988C1}" />
        <r
          ds=""
          id="{7DFD9396-CB94-4174-9721-9419A2AA68E3}"
          par="MapType=terrain&amp;CenterLocation=-5.055576%2C3.803790&amp;ZoomLevel=15&amp;EnableCenterMapControl&amp;EnableZoomControl=1&amp;EnableMapTypeControl=1&amp;EnableScaleControl&amp;EnableStreetViewControl&amp;EnableRotateControl"
          ph="/page-layout/section/col-narrow-1"
          uid="{1274F635-B4D2-4D41-9E99-56D2CE8615F6}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r
          id="{7074CA39-734D-4953-A3D5-B7D09C37CE3B}"
          par="UseStaticPlaceholderNames=1"
          ph="/footer/section"
          uid="{025588CB-DFC0-4B02-8223-0015C525AE52}" />
        <r
          ds="{0D3418C0-C90E-46CE-A963-C7D79348C5D0}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-1"
          uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r
          ds="{73D641B9-190A-404E-A57C-3C60DA805E8B}"
          id="{CA748838-E6D5-4BAD-9126-CAD10DD1B0DB}"
          par="Background=%7bBD2F308A-E00A-4372-ADBB-BD64712A54FA%7d"
          ph="/footer/section/col-narrow-2"
          uid="{84124EE2-E678-4144-8316-0D6874866604}" />
        <r
          ds="{7769A970-9686-4A9F-B4D1-1190916CBCE4}"
          id="{781C6B36-4B02-46EA-8ADC-B92A11877F10}"
          par="Background=%7bBD2F308A-E00A-4372-ADBB-BD64712A54FA%7d"
          ph="/footer/section/col-narrow-3"
          uid="{E200C0B1-2874-4DC9-924A-457DB47EFF0B}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{20AB9BAA-C112-4567-A701-564423E650D2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ee2f208-1fee-42fc-8051-6696d49a92bf"
      Hint: OpenGraphTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160906T012857Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
    - ID: "f12c22bb-e57d-4fab-96e1-1229e4e7ff0e"
      Hint: MapPointName
      Value: $name
