---
ID: "7bd6ece6-e26a-45f3-ac78-9cdcb69654b4"
Parent: "4be6922e-4386-410e-a86e-f342b9abb286"
Template: "4be6922e-4386-410e-a86e-f342b9abb286"
Path: /sitecore/templates/Project/Group/Page Types/Event List/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{FA3C818B-3B70-490A-BF49-F6D6A14E2B43}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{17857EED-0386-4911-89EC-C29D9C018237}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{E6CA18D8-321D-4105-9C38-0622E94BE400}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{EF51B238-7CE2-4E39-AB87-D05424735160}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{07C9FE71-A5E2-4E5F-B276-5F2B73481D44}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{7BD25BD6-C6C4-4FBE-9828-D29A39A2FEC9}" />
        <r
          id="{53B085DB-6824-4941-9F28-9011CB151832}"
          ph="navbar-right"
          uid="{FBDB4313-35B5-4C26-A586-17F48FD2DC41}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{75551DEC-A457-43A3-B76F-91742B5DDE93}" />
        <r
          id="{604ECBB6-2BBF-45AF-AC6E-BA9F853E7A03}"
          ph="navbar-activity"
          uid="{462763BC-EC80-4FBA-9714-B63A87B43259}" />
        <r
          id="{2695013C-DD51-410B-9983-F271F16C727D}"
          ph="navbar-activity"
          uid="{3555E24E-FBE9-4D81-AAC7-50408AA45EF0}" />
        <r
          ds="{E3F5B510-54B3-4FEE-B7A8-0FBA14121AC1}"
          id="{8C3A2CFC-18FB-4BF5-8584-50EA88978ED6}"
          ph="navbar-activity"
          uid="{9C8A45F2-7008-42C1-8B8A-80A88825C1D8}" />
        <r
          id="{26B33DEB-F1DB-4338-B043-AAF2F90E04A3}"
          ph="page-layout"
          uid="{1DF746C3-2D29-43E6-9DE2-05622DED6F97}" />
        <r
          id="{45B8E1D9-D522-49E0-B9B7-04C965CC7089}"
          ph="page-header"
          uid="{3CDF4DD8-28A4-4185-8C09-A73CAA4633F7}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{A3CA17FF-693C-46F1-87AA-B8C1833F1890}" />
        <r
          id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}"
          par="UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{66422117-69C1-4B62-9323-482F16C4F244}" />
        <r
          id="{E425E108-2EE5-4EFE-9DA9-76B1698C415C}"
          ph="col-huge"
          uid="{3900ADC1-26E3-45C2-935C-1BC12D4E228A}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{E2040FB7-4151-456D-9315-5973E4EB4D9D}" />
        <r
          id="{7074CA39-734D-4953-A3D5-B7D09C37CE3B}"
          par="UseStaticPlaceholderNames=1"
          ph="/footer/section"
          uid="{025588CB-DFC0-4B02-8223-0015C525AE52}" />
        <r
          ds="{0D3418C0-C90E-46CE-A963-C7D79348C5D0}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-1"
          uid="{0E0C6DCA-1A29-4975-84D7-E99498A64A72}" />
        <r
          ds="{73D641B9-190A-404E-A57C-3C60DA805E8B}"
          id="{CA748838-E6D5-4BAD-9126-CAD10DD1B0DB}"
          par="Background=%7bBD2F308A-E00A-4372-ADBB-BD64712A54FA%7d"
          ph="/footer/section/col-narrow-2"
          uid="{84124EE2-E678-4144-8316-0D6874866604}" />
        <r
          ds="{7769A970-9686-4A9F-B4D1-1190916CBCE4}"
          id="{781C6B36-4B02-46EA-8ADC-B92A11877F10}"
          par="Background=%7bBD2F308A-E00A-4372-ADBB-BD64712A54FA%7d"
          ph="/footer/section/col-narrow-3"
          uid="{E200C0B1-2874-4DC9-924A-457DB47EFF0B}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{A3BAD4D4-8E21-4B30-8C4C-B04163653D62}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{20AB9BAA-C112-4567-A701-564423E650D2}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0ee2f208-1fee-42fc-8051-6696d49a92bf"
      Hint: OpenGraphTitle
      Value: $name
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160906T014532Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
    - ID: "c30a013f-3cc8-4961-9837-1c483277084a"
      Hint: Title
      Value: $name
    - ID: "ca0479ce-0bfe-4522-83de-ba688b380a78"
      Hint: BrowserTitle
      Value: $name
