---
ID: "48337615-1022-4b40-9e0c-efcbbe9f8617"
Parent: "6511fa55-3087-49c4-b8ee-10f6e699c52c"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Feature/Events/VenueSettings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/tent.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: |
    {1930BBEB-7805-471A-A3BE-4858AC7CF696}
    {BDCD65C3-1DF8-4BEF-9F6F-976F47EA4BD3}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161214T095614Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
